[package]
authors = ["Nicole Mazzuca <npmazzuca@gmail.com>"]
name = "cafec"
version = "0.1.0"

[[bin]]
name = "cafec"

[dependencies]
clap = "2.26.0"
ucd = "0.1.1"
unicode-normalization = "0.1.5"
unicode-xid = "0.1.0"
